/*
 * Seq API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package seq

import (
	"encoding/json"
)

// TelemetryReplyEmail struct for TelemetryReplyEmail
type TelemetryReplyEmail struct {
	Id *string `json:"Id,omitempty"`
	Name *string `json:"Name,omitempty"`
	Value *string `json:"Value,omitempty"`
}

// NewTelemetryReplyEmail instantiates a new TelemetryReplyEmail object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTelemetryReplyEmail() *TelemetryReplyEmail {
	this := TelemetryReplyEmail{}
	return &this
}

// NewTelemetryReplyEmailWithDefaults instantiates a new TelemetryReplyEmail object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTelemetryReplyEmailWithDefaults() *TelemetryReplyEmail {
	this := TelemetryReplyEmail{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *TelemetryReplyEmail) GetId() string {
	if o == nil || o.Id == nil {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TelemetryReplyEmail) GetIdOk() (*string, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *TelemetryReplyEmail) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *TelemetryReplyEmail) SetId(v string) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *TelemetryReplyEmail) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TelemetryReplyEmail) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *TelemetryReplyEmail) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *TelemetryReplyEmail) SetName(v string) {
	o.Name = &v
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *TelemetryReplyEmail) GetValue() string {
	if o == nil || o.Value == nil {
		var ret string
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TelemetryReplyEmail) GetValueOk() (*string, bool) {
	if o == nil || o.Value == nil {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *TelemetryReplyEmail) HasValue() bool {
	if o != nil && o.Value != nil {
		return true
	}

	return false
}

// SetValue gets a reference to the given string and assigns it to the Value field.
func (o *TelemetryReplyEmail) SetValue(v string) {
	o.Value = &v
}

func (o TelemetryReplyEmail) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Id != nil {
		toSerialize["Id"] = o.Id
	}
	if o.Name != nil {
		toSerialize["Name"] = o.Name
	}
	if o.Value != nil {
		toSerialize["Value"] = o.Value
	}
	return json.Marshal(toSerialize)
}

type NullableTelemetryReplyEmail struct {
	value *TelemetryReplyEmail
	isSet bool
}

func (v NullableTelemetryReplyEmail) Get() *TelemetryReplyEmail {
	return v.value
}

func (v *NullableTelemetryReplyEmail) Set(val *TelemetryReplyEmail) {
	v.value = val
	v.isSet = true
}

func (v NullableTelemetryReplyEmail) IsSet() bool {
	return v.isSet
}

func (v *NullableTelemetryReplyEmail) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTelemetryReplyEmail(val *TelemetryReplyEmail) *NullableTelemetryReplyEmail {
	return &NullableTelemetryReplyEmail{value: val, isSet: true}
}

func (v NullableTelemetryReplyEmail) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTelemetryReplyEmail) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


