/*
 * Seq API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package seq

import (
	"encoding/json"
)

// OpenIdConnectEndSessionRedirectUri struct for OpenIdConnectEndSessionRedirectUri
type OpenIdConnectEndSessionRedirectUri struct {
	Id string `json:"Id"`
	Name string `json:"Name"`
	Value *string `json:"Value,omitempty"`
}

// NewOpenIdConnectEndSessionRedirectUri instantiates a new OpenIdConnectEndSessionRedirectUri object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOpenIdConnectEndSessionRedirectUri(id string, name string, ) *OpenIdConnectEndSessionRedirectUri {
	this := OpenIdConnectEndSessionRedirectUri{}
	this.Id = id
	this.Name = name
	return &this
}

// NewOpenIdConnectEndSessionRedirectUriWithDefaults instantiates a new OpenIdConnectEndSessionRedirectUri object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOpenIdConnectEndSessionRedirectUriWithDefaults() *OpenIdConnectEndSessionRedirectUri {
	this := OpenIdConnectEndSessionRedirectUri{}
	return &this
}

// GetId returns the Id field value
func (o *OpenIdConnectEndSessionRedirectUri) GetId() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *OpenIdConnectEndSessionRedirectUri) GetIdOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *OpenIdConnectEndSessionRedirectUri) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *OpenIdConnectEndSessionRedirectUri) GetName() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *OpenIdConnectEndSessionRedirectUri) GetNameOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *OpenIdConnectEndSessionRedirectUri) SetName(v string) {
	o.Name = v
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *OpenIdConnectEndSessionRedirectUri) GetValue() string {
	if o == nil || o.Value == nil {
		var ret string
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OpenIdConnectEndSessionRedirectUri) GetValueOk() (*string, bool) {
	if o == nil || o.Value == nil {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *OpenIdConnectEndSessionRedirectUri) HasValue() bool {
	if o != nil && o.Value != nil {
		return true
	}

	return false
}

// SetValue gets a reference to the given string and assigns it to the Value field.
func (o *OpenIdConnectEndSessionRedirectUri) SetValue(v string) {
	o.Value = &v
}

func (o OpenIdConnectEndSessionRedirectUri) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["Id"] = o.Id
	}
	if true {
		toSerialize["Name"] = o.Name
	}
	if o.Value != nil {
		toSerialize["Value"] = o.Value
	}
	return json.Marshal(toSerialize)
}

type NullableOpenIdConnectEndSessionRedirectUri struct {
	value *OpenIdConnectEndSessionRedirectUri
	isSet bool
}

func (v NullableOpenIdConnectEndSessionRedirectUri) Get() *OpenIdConnectEndSessionRedirectUri {
	return v.value
}

func (v *NullableOpenIdConnectEndSessionRedirectUri) Set(val *OpenIdConnectEndSessionRedirectUri) {
	v.value = val
	v.isSet = true
}

func (v NullableOpenIdConnectEndSessionRedirectUri) IsSet() bool {
	return v.isSet
}

func (v *NullableOpenIdConnectEndSessionRedirectUri) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOpenIdConnectEndSessionRedirectUri(val *OpenIdConnectEndSessionRedirectUri) *NullableOpenIdConnectEndSessionRedirectUri {
	return &NullableOpenIdConnectEndSessionRedirectUri{value: val, isSet: true}
}

func (v NullableOpenIdConnectEndSessionRedirectUri) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOpenIdConnectEndSessionRedirectUri) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


