/*
 * Seq API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package seq

import (
	"encoding/json"
)

// BackupUtcTimeOfDay struct for BackupUtcTimeOfDay
type BackupUtcTimeOfDay struct {
	Id *string `json:"Id,omitempty"`
	Name *string `json:"Name,omitempty"`
	Value *string `json:"Value,omitempty"`
}

// NewBackupUtcTimeOfDay instantiates a new BackupUtcTimeOfDay object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBackupUtcTimeOfDay() *BackupUtcTimeOfDay {
	this := BackupUtcTimeOfDay{}
	return &this
}

// NewBackupUtcTimeOfDayWithDefaults instantiates a new BackupUtcTimeOfDay object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBackupUtcTimeOfDayWithDefaults() *BackupUtcTimeOfDay {
	this := BackupUtcTimeOfDay{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *BackupUtcTimeOfDay) GetId() string {
	if o == nil || o.Id == nil {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BackupUtcTimeOfDay) GetIdOk() (*string, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *BackupUtcTimeOfDay) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *BackupUtcTimeOfDay) SetId(v string) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *BackupUtcTimeOfDay) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BackupUtcTimeOfDay) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *BackupUtcTimeOfDay) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *BackupUtcTimeOfDay) SetName(v string) {
	o.Name = &v
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *BackupUtcTimeOfDay) GetValue() string {
	if o == nil || o.Value == nil {
		var ret string
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BackupUtcTimeOfDay) GetValueOk() (*string, bool) {
	if o == nil || o.Value == nil {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *BackupUtcTimeOfDay) HasValue() bool {
	if o != nil && o.Value != nil {
		return true
	}

	return false
}

// SetValue gets a reference to the given string and assigns it to the Value field.
func (o *BackupUtcTimeOfDay) SetValue(v string) {
	o.Value = &v
}

func (o BackupUtcTimeOfDay) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Id != nil {
		toSerialize["Id"] = o.Id
	}
	if o.Name != nil {
		toSerialize["Name"] = o.Name
	}
	if o.Value != nil {
		toSerialize["Value"] = o.Value
	}
	return json.Marshal(toSerialize)
}

type NullableBackupUtcTimeOfDay struct {
	value *BackupUtcTimeOfDay
	isSet bool
}

func (v NullableBackupUtcTimeOfDay) Get() *BackupUtcTimeOfDay {
	return v.value
}

func (v *NullableBackupUtcTimeOfDay) Set(val *BackupUtcTimeOfDay) {
	v.value = val
	v.isSet = true
}

func (v NullableBackupUtcTimeOfDay) IsSet() bool {
	return v.isSet
}

func (v *NullableBackupUtcTimeOfDay) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBackupUtcTimeOfDay(val *BackupUtcTimeOfDay) *NullableBackupUtcTimeOfDay {
	return &NullableBackupUtcTimeOfDay{value: val, isSet: true}
}

func (v NullableBackupUtcTimeOfDay) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBackupUtcTimeOfDay) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


