/*
 * Seq API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package seq

import (
	"encoding/json"
)

// MinimumFreeStorageSpace struct for MinimumFreeStorageSpace
type MinimumFreeStorageSpace struct {
	Id string `json:"Id"`
	Name string `json:"Name"`
	Value *int32 `json:"Value,omitempty"`
}

// NewMinimumFreeStorageSpace instantiates a new MinimumFreeStorageSpace object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMinimumFreeStorageSpace(id string, name string, ) *MinimumFreeStorageSpace {
	this := MinimumFreeStorageSpace{}
	this.Id = id
	this.Name = name
	return &this
}

// NewMinimumFreeStorageSpaceWithDefaults instantiates a new MinimumFreeStorageSpace object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMinimumFreeStorageSpaceWithDefaults() *MinimumFreeStorageSpace {
	this := MinimumFreeStorageSpace{}
	return &this
}

// GetId returns the Id field value
func (o *MinimumFreeStorageSpace) GetId() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *MinimumFreeStorageSpace) GetIdOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *MinimumFreeStorageSpace) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *MinimumFreeStorageSpace) GetName() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *MinimumFreeStorageSpace) GetNameOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *MinimumFreeStorageSpace) SetName(v string) {
	o.Name = v
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *MinimumFreeStorageSpace) GetValue() int32 {
	if o == nil || o.Value == nil {
		var ret int32
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MinimumFreeStorageSpace) GetValueOk() (*int32, bool) {
	if o == nil || o.Value == nil {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *MinimumFreeStorageSpace) HasValue() bool {
	if o != nil && o.Value != nil {
		return true
	}

	return false
}

// SetValue gets a reference to the given int32 and assigns it to the Value field.
func (o *MinimumFreeStorageSpace) SetValue(v int32) {
	o.Value = &v
}

func (o MinimumFreeStorageSpace) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["Id"] = o.Id
	}
	if true {
		toSerialize["Name"] = o.Name
	}
	if o.Value != nil {
		toSerialize["Value"] = o.Value
	}
	return json.Marshal(toSerialize)
}

type NullableMinimumFreeStorageSpace struct {
	value *MinimumFreeStorageSpace
	isSet bool
}

func (v NullableMinimumFreeStorageSpace) Get() *MinimumFreeStorageSpace {
	return v.value
}

func (v *NullableMinimumFreeStorageSpace) Set(val *MinimumFreeStorageSpace) {
	v.value = val
	v.isSet = true
}

func (v NullableMinimumFreeStorageSpace) IsSet() bool {
	return v.isSet
}

func (v *NullableMinimumFreeStorageSpace) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMinimumFreeStorageSpace(val *MinimumFreeStorageSpace) *NullableMinimumFreeStorageSpace {
	return &NullableMinimumFreeStorageSpace{value: val, isSet: true}
}

func (v NullableMinimumFreeStorageSpace) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMinimumFreeStorageSpace) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


