/*
 * Seq API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package seq

import (
	"encoding/json"
)

// CheckForPackageUpdates struct for CheckForPackageUpdates
type CheckForPackageUpdates struct {
	Id string `json:"Id"`
	Name string `json:"Name"`
	Value *bool `json:"Value,omitempty"`
}

// NewCheckForPackageUpdates instantiates a new CheckForPackageUpdates object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCheckForPackageUpdates(id string, name string, ) *CheckForPackageUpdates {
	this := CheckForPackageUpdates{}
	this.Id = id
	this.Name = name
	return &this
}

// NewCheckForPackageUpdatesWithDefaults instantiates a new CheckForPackageUpdates object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCheckForPackageUpdatesWithDefaults() *CheckForPackageUpdates {
	this := CheckForPackageUpdates{}
	return &this
}

// GetId returns the Id field value
func (o *CheckForPackageUpdates) GetId() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *CheckForPackageUpdates) GetIdOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *CheckForPackageUpdates) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *CheckForPackageUpdates) GetName() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CheckForPackageUpdates) GetNameOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CheckForPackageUpdates) SetName(v string) {
	o.Name = v
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *CheckForPackageUpdates) GetValue() bool {
	if o == nil || o.Value == nil {
		var ret bool
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CheckForPackageUpdates) GetValueOk() (*bool, bool) {
	if o == nil || o.Value == nil {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *CheckForPackageUpdates) HasValue() bool {
	if o != nil && o.Value != nil {
		return true
	}

	return false
}

// SetValue gets a reference to the given bool and assigns it to the Value field.
func (o *CheckForPackageUpdates) SetValue(v bool) {
	o.Value = &v
}

func (o CheckForPackageUpdates) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["Id"] = o.Id
	}
	if true {
		toSerialize["Name"] = o.Name
	}
	if o.Value != nil {
		toSerialize["Value"] = o.Value
	}
	return json.Marshal(toSerialize)
}

type NullableCheckForPackageUpdates struct {
	value *CheckForPackageUpdates
	isSet bool
}

func (v NullableCheckForPackageUpdates) Get() *CheckForPackageUpdates {
	return v.value
}

func (v *NullableCheckForPackageUpdates) Set(val *CheckForPackageUpdates) {
	v.value = val
	v.isSet = true
}

func (v NullableCheckForPackageUpdates) IsSet() bool {
	return v.isSet
}

func (v *NullableCheckForPackageUpdates) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCheckForPackageUpdates(val *CheckForPackageUpdates) *NullableCheckForPackageUpdates {
	return &NullableCheckForPackageUpdates{value: val, isSet: true}
}

func (v NullableCheckForPackageUpdates) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCheckForPackageUpdates) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


