/*
 * Seq API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package seq

import (
	"encoding/json"
)

// BackupsToKeep struct for BackupsToKeep
type BackupsToKeep struct {
	Id string `json:"Id"`
	Name string `json:"Name"`
	Value *int32 `json:"Value,omitempty"`
}

// NewBackupsToKeep instantiates a new BackupsToKeep object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBackupsToKeep(id string, name string, ) *BackupsToKeep {
	this := BackupsToKeep{}
	this.Id = id
	this.Name = name
	return &this
}

// NewBackupsToKeepWithDefaults instantiates a new BackupsToKeep object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBackupsToKeepWithDefaults() *BackupsToKeep {
	this := BackupsToKeep{}
	return &this
}

// GetId returns the Id field value
func (o *BackupsToKeep) GetId() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *BackupsToKeep) GetIdOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *BackupsToKeep) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *BackupsToKeep) GetName() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *BackupsToKeep) GetNameOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *BackupsToKeep) SetName(v string) {
	o.Name = v
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *BackupsToKeep) GetValue() int32 {
	if o == nil || o.Value == nil {
		var ret int32
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BackupsToKeep) GetValueOk() (*int32, bool) {
	if o == nil || o.Value == nil {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *BackupsToKeep) HasValue() bool {
	if o != nil && o.Value != nil {
		return true
	}

	return false
}

// SetValue gets a reference to the given int32 and assigns it to the Value field.
func (o *BackupsToKeep) SetValue(v int32) {
	o.Value = &v
}

func (o BackupsToKeep) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["Id"] = o.Id
	}
	if true {
		toSerialize["Name"] = o.Name
	}
	if o.Value != nil {
		toSerialize["Value"] = o.Value
	}
	return json.Marshal(toSerialize)
}

type NullableBackupsToKeep struct {
	value *BackupsToKeep
	isSet bool
}

func (v NullableBackupsToKeep) Get() *BackupsToKeep {
	return v.value
}

func (v *NullableBackupsToKeep) Set(val *BackupsToKeep) {
	v.value = val
	v.isSet = true
}

func (v NullableBackupsToKeep) IsSet() bool {
	return v.isSet
}

func (v *NullableBackupsToKeep) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBackupsToKeep(val *BackupsToKeep) *NullableBackupsToKeep {
	return &NullableBackupsToKeep{value: val, isSet: true}
}

func (v NullableBackupsToKeep) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBackupsToKeep) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


