/*
 * Seq API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package seq

import (
	"encoding/json"
)

// OpenIdConnectScopes struct for OpenIdConnectScopes
type OpenIdConnectScopes struct {
	Id string `json:"Id"`
	Name string `json:"Name"`
	Value *string `json:"Value,omitempty"`
}

// NewOpenIdConnectScopes instantiates a new OpenIdConnectScopes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOpenIdConnectScopes(id string, name string, ) *OpenIdConnectScopes {
	this := OpenIdConnectScopes{}
	this.Id = id
	this.Name = name
	return &this
}

// NewOpenIdConnectScopesWithDefaults instantiates a new OpenIdConnectScopes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOpenIdConnectScopesWithDefaults() *OpenIdConnectScopes {
	this := OpenIdConnectScopes{}
	return &this
}

// GetId returns the Id field value
func (o *OpenIdConnectScopes) GetId() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *OpenIdConnectScopes) GetIdOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *OpenIdConnectScopes) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *OpenIdConnectScopes) GetName() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *OpenIdConnectScopes) GetNameOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *OpenIdConnectScopes) SetName(v string) {
	o.Name = v
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *OpenIdConnectScopes) GetValue() string {
	if o == nil || o.Value == nil {
		var ret string
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OpenIdConnectScopes) GetValueOk() (*string, bool) {
	if o == nil || o.Value == nil {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *OpenIdConnectScopes) HasValue() bool {
	if o != nil && o.Value != nil {
		return true
	}

	return false
}

// SetValue gets a reference to the given string and assigns it to the Value field.
func (o *OpenIdConnectScopes) SetValue(v string) {
	o.Value = &v
}

func (o OpenIdConnectScopes) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["Id"] = o.Id
	}
	if true {
		toSerialize["Name"] = o.Name
	}
	if o.Value != nil {
		toSerialize["Value"] = o.Value
	}
	return json.Marshal(toSerialize)
}

type NullableOpenIdConnectScopes struct {
	value *OpenIdConnectScopes
	isSet bool
}

func (v NullableOpenIdConnectScopes) Get() *OpenIdConnectScopes {
	return v.value
}

func (v *NullableOpenIdConnectScopes) Set(val *OpenIdConnectScopes) {
	v.value = val
	v.isSet = true
}

func (v NullableOpenIdConnectScopes) IsSet() bool {
	return v.isSet
}

func (v *NullableOpenIdConnectScopes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOpenIdConnectScopes(val *OpenIdConnectScopes) *NullableOpenIdConnectScopes {
	return &NullableOpenIdConnectScopes{value: val, isSet: true}
}

func (v NullableOpenIdConnectScopes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOpenIdConnectScopes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


